### PR TITLE
Upgrade to .Net8

### PR DESCRIPTION
**Pull request by GeirMG**
@OsirisTerje @martinmine This is completely untested. How can I test this?

### CODE REVIEW

**Comment by GeirMG** [comment]
This replaces all dependabots PR's.

**Review by martinmine — COMMENTED** [review]
We should also bump the major version as part of this PR

**Review by martinmine — APPROVED** [review]

**Comment by GeirMG** [comment]
> We should also bump the major version as part of this PR

It is - or am I missing something?

**Comment by GeirMG** [comment]
> > We should also bump the major version as part of this PR
> 
> It is - or am I missing something?

Ah, too long ago. I fixed this after your comment :)

**Comment by OsirisTerje** [comment]
@GeirMG 

> This is completely untested. How can I test this?

Publish this package as a beta release, e.g. beta.1.  Then use e.g. personoppslagAPI and upgrade to this beta package - and then run the integrationtests.  If that works, you're good to go.

**Comment by GeirMG** [comment]
> @GeirMG
> 
> > This is completely untested. How can I test this?
> 
> Publish this package as a beta release, e.g. beta.1. Then use e.g. personoppslagAPI and upgrade to this beta package - and then run the integrationtests. If that works, you're good to go.

Added beta1 tag to version.

**Pull request merged**
